ChangeLog
REGRESS

The problem with Mac OS X is that by default the ulimit setting for core dumps is set to zero.  This fixes REGRESS to make it be unlmited.  Along the way, if a.out is not there it will run make and exit early if make fails.
I have tried to use very portable constructs in the shell script.

Fix REGRESS so all tests run on Mac OS X.

---

bugs-fixed/README
bugs-fixed/missing-precision.awk
bugs-fixed/missing-precision.ok
run.c

This adds a check for when the precision argument is missing (e.g., `printf("%*s")`). I've added an example program to `bugs-fixed`.

Check for format character precision argument before using it

---

lex.c

Improve error reporting messages

---

main.c

The check for the explcit end of arguments flag (`--`) uses `strncmp` with a length of 2, instead of 3 (`sizeof ("--")`), which means that it treats all flags that begin with two dashes as the end. This can create some confusing messages:
```
cpm@enlil ~/src/awk : end-of-args % ./old-nawk --help
./old-nawk: no program given
cpm@enlil ~/src/awk : end-of-args (2) % ./old-nawk --file bugs-fixed/a-format.awk 
./old-nawk: syntax error at source line 1
context is
>>> bugs-fixed/a-format. <<< awk
./old-nawk: bailing out at source line 1
```
I've switched this back to using `strcmp`, which is what it used before ~2007, when the `-version` and `--version` flags were added. Using the above flags now produces the "unknown option" message:
```
cpmcpm@enlil ~/src/awk : end-of-args % ./a.out --help …
```

Flags that begin with "--" should not be treated as end of args

---

b.c

This fixes using the `[[:cntrl:]]` character class. Because the string for the class currently gets terminated early, it matches anything. For example:
```
% gawk 'BEGIN { print ("^G" ~ /[[:cntrl:]]/), ("f" ~ /[[:cntrl:]]/); }'
1 0
% mawk 'BEGIN { print ("^G" ~ /[[:cntrl:]]/), ("f" ~ /[[:cntrl:]]/); }'
1 0
% ./old-nawk 'BEGIN { print ("^G" ~ /[[:cntrl:]]/), ("f" ~ /[[:cntrl:]]/); }' 
1 1
% ./a.out 'BEGIN { print ("^G" ~ /[[:cntrl:]]/), ("f" ~ /[[:cntrl:]]/); }' 
1 0
```
`a.out` is with the fix, `old-nawk` is before the fix.

Fix regular expressions containing [[:cntrl:]]

---

lib.c

This fixes an issue with the initial buffer size for `fields`, so that it contains enough space for the two possible terminating `\0`'s in [fldbld()](https://github.com/onetrueawk/awk/blob/e8c280034fad30d5234590ac3c62ebd0fe3d25dd/lib.c#L305-L307) (which already accounts for the needed space [here](https://github.com/onetrueawk/awk/blob/e8c280034fad30d5234590ac3c62ebd0fe3d25dd/lib.c#L280); the [refldbld()](https://github.com/onetrueawk/awk/blob/e8c280034fad30d5234590ac3c62ebd0fe3d25dd/lib.c#L442) allocation seems to be unreachable due to the `fldbld()` check).  The easiest way I've found to reproduce this is on illumos using the memory allocator's [debugging features](http://illumos.org/man/3malloc/umem_debug) to detect the overflow when the buffer gets freed:
```
% …
```

Fix initial "fields" buffer size

---

.gitignore
makefile
maketab.c

If your generated files are considered outputs that live elsewhere, you
need a way to tell maketab where ytab.h actually is.
Specifically, I'm trying to avoid checking in generated files in
Android's AOSP tree's copy of one-true-awk.

maketab: support build systems with read-only source.

---

makefile

Fixes in make file to support cross-build because maketab is a host tool and should be compiled with host compiler

Fix cross-build

---

FIXES
awk.h
main.c
run.c

If you `delete SYMTAB`, it frees the table and everything in it. This can lead to reading from freed memory later on:
```
% printf "a b c\nd e f\n" | ./a.out '{ delete SYMTAB; print $2; }'
b
./a.out: illegal field $(), name "4"
input record number 2, file
source line number 1
% printf "a b c\nd e f\n" | LD_PRELOAD=/usr/lib/libumem.so UMEM_DEBUG=default ./a.out '{ delete SYMTAB; print $2; }'
zsh: done                              printf "a b c\nd e f\n" |
zsh: segmentation fault (core dumped)  LD_PRELOAD=/usr/lib/libumem.so UMEM_DEBUG=default ./a.out
```
I've added a guard to prevent deleting the table, or anything from it, and produce a `FATAL` error message instead:
```
% printf "a b c\nd e f\n" | ./a.out '{ delete SYMTAB; print $2; }'
./a.out: cannot delete SYMTAB or its elements
input …
```

Disallow deleting SYMTAB and its elements

---

lib.c
proto.h
tran.c

The POSIX specification for `awk(1)` [specifies](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html):
> Before the first reference to a field in the record is evaluated, the record shall be split into fields, according to the rules in Regular Expressions, using the value of FS that was current at the time the record was read.
Since `nawk` splits the fields lazily at the point where they are first referenced, [these lines](https://github.com/onetrueawk/awk/blob/20180827/lib.c#L193-L196) were added in 1996 to save the value:
```
Jun 28, 1996:
changed field-splitting to conform to posix definition: fields are
split using the value of FS at the time of input; it used to be
the value when the field or NF was first referred to, a much less
predictable definition.  thanks to …
```

Update field-splitting behaviour to match POSIX definition

---

FIXES
b.c
main.c
tran.c

Support POSIX-specified C-style escape sequences "\a" (alarm)
and "\v" (vertical tab) in command line arguments and regular
expressions, further to the support for them in strings added on
Apr 9, 1989. These now no longer match as literal "a" and "v"
characters (as they don't on gawk and mawk).
IOW, lex.c already supported these (lines 390-391 as of 4e343460);
the support needed to be added to b.c and tran.c.
Relevant POSIX reference:
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html#tag_20_06_13_04

Add support for "\a" and "\v" to regex and command line args

---

README

"buildmac" file is no longer supplied.

Drop Mac OS 9 reference

---

awk.h
b.c

When matching a caret, the expression	`f->gototab[s][c] = f->curstat;` in
cgoto() will index the 2D-array gototab with [s][261]. However, gototab
is declared as being of size [NSTATES][NCHARS], so [32][259]. Therefore,
this assignment will write to the state for character 0x1.
I'm not sure how to create a regression test for this, but increasing the
array size to HAT+1 values fixes the error and the tests still pass.
I found this issue while running awk on a CHERI system with sub-object
protection enabled. On x86, this can be reproduced by compiling awk
with -fsanitize=undefined.

Fix out-of-bounds access in gototab array for caret character

---

lex.c

As it is never dereferenced in the n == -1 case it shouldn't cause any
problems. However, UBSAN complains about this, so it is required to run
the tests when compiling with -fsanitize=undefined.
I was able to run `make test` with -fsanitize=undefined after applying this on top of #47.

Avoid creating an out-of-bounds pointer in word()

---

testdir/T.csconcat

On case-insensitive file systems (i.e.: macOS), `T.concat` and `t.concat` are the same file, so these conflicted. This commit renames `T.concat` to avoid the conflict.

rename T.concat to T.csconcat to avoid case-insensitive conflict

---

FIXES
run.c
testdir/T.misc

An input/output error indicates a fatal condition, even if it occurs when closing a file. Awk should not return success on I/O error, but treat I/O errors as it already treats write errors.
Test case:
```
$ (trap '' PIPE; awk 'BEGIN { print "hi"; }'; echo "E $?" >&2) | :
awk: i/o error occurred while closing /dev/stdout
source line number 1
E 2
```
The test case pipes a line into a dummy command that reads no input, with SIGPIPE ignored so we rely on awk's own I/O checking. No write error is detected, because the pipe is buffered; the
broken pipe is only detected as an I/O error on closing stdout.
Before this commit, "E 0" was printed (indicating status 0/success) because an I/O error merely produced a warning. A shell script was unable to detect the I/O error using the exit status.

Make I/O errors fatal instead of mere warnings

---

lib.c

MB_CUR_MAX is the maximum number of bytes in a multibyte character
for the current locale, and might not be a constant expression.
MB_LEN_MAX is the maximum number of bytes in a multibyte character
for any locale, and always expands to a constant-expression.

Use MB_LEN_MAX instead of MB_CUR_MAX to avoid VLA

---

lib.c
proto.h
run.c

- add missing initializers
- fix sign-compare warnings
- fix shadowed variable
- remove parameter names from the 2 prototypes that had them for consistency.
With those changes, NetBSD is now running 20200218 unchanged.

More minor fixes:

---

lex.c
makefile

Crash found with https://source.android.com/devices/tech/debug/hwasan
but also detectable by regular ASan. Here's an ASan crash:
==215690==ERROR: AddressSanitizer: global-buffer-overflow on address
0x55d90f8da140 at pc 0x55d90f8b7503 bp 0x7ffd3dae6100 sp 0x7ffd3dae60f8
READ of size 4 at 0x55d90f8da140 thread T0
#0 0x55d90f8b7502 in word /tmp/awk/lex.c:496
#1 0x55d90f8b939f in yylex /tmp/awk/lex.c:191
#2 0x55d90f894ab9 in yyparse /tmp/awk/awkgram.tab.c:2366
#3 0x55d90f89edc2 in main /tmp/awk/main.c:216
#4 0x7ff263a78bba in __libc_start_main ../csu/libc-start.c:308
#5 0x55d90f8945a9 in _start (/tmp/awk/a.out+0x115a9)
0x55d90f8da141 is located 0 bytes to the right of global variable
'infunc' defined in 'awkgram.y:35:6' (0x55d90f8da140) of size 1
SUMMARY: AddressSanitizer: …

Fix hwasan global overflow.

---

awk.h
main.c
proto.h

`_Noreturn` is standard C and in my opinion, less ugly than `__attribute__((__noreturn__))`.
Should I use `noreturn` instead and `#include <stdnoreturn.h>`?

Replace __attribute__((__noreturn__)) with _Noreturn.

---

run.c

The errcheck() function treats an errno of ERANGE or EDOM as something to report, so make sure errno is set to zero before invoking a function to check so that a previous such errno value won't result in a false positive.  This could happen simply due to input line fields that looked enough like floating-point input to trigger ERANGE.
Bug reported by Jordan Geoghegan, fix from Philip Guenther.
The bug can be reproduced via:  echo 5e58386636aa775c2106140445 | awk 'END {print log(2)}'
An alternate fix is to clear errno on strtod() failure in is_number() but that seems like a more fragile solution.

Clear errno before using errcheck() to avoid spurious errors.

---

awk.h
b.c
lib.c
main.c
parse.c
run.c
tran.c

POSIX specifies a dprintf function that operates on an fd instead of a stdio stream.  Using upper case for macros is more idiomatic too.  We no longer need to use an extra set of parentheses for debugging printf statements.

Rename dprintf to DPRINTF and use C99 cpp variadic arguments.

---

run.c

The optimization in commit 1d6ddfd9c0ed7119c0601474cded3a385068e886 reintroduced the regression that was fixed in commit e26237434fb769d9c1ea239101eb5b24be588eea.
The regression can be reproduced with the bugs-fixed/concat-assign-same.awk test added by the latter commit.

Fix concatenation regression

---

run.c

Commit 0d8778bbbb415810bfd126694a38b6bf4b71e79c reintroduced a regression that was fixed in commit 97a4b7ed215ae6446d13fe0eab15b5b3ae4da7da. The length of SUBSEP needs to be rechecked after calling execute(), in case SUBSEP itself has been changed.
The regression can be reproduced with the bugs-fixed/subsep-overflow.awk test added by the latter commit. The output is incorrect (e.g. on the first line 13503 should be 27001) and awk may segfault due to an out-of-bounds write.

Fix regression with changed SUBSEP in subscript

---

run.c

If closefile() is called on std{in,out,err}, freopen() /dev/null instead, otherwise, awk will continue trying to perform I/O on a closed stdio stream.  In closeall(), avoid closing std{in,out,err}.

Avoid using stdio streams after they have been closed.

---

testdir/T.errmsg

Some mishap with a heredoc delimiter prevented the tests from running.

Fix the T.errmsg test

---

lib.c

If awk prints an error message while when compile_time is still set to ERROR_PRINTING, don't try to print the context since there is none.  This can happen due to a problem with, e.g., unknown command line options.

Don't print extra newlines on error before awk starts parsing.

---

awk.1
lex.c
lib.c
proto.h
run.c
tran.c

1. Revise the is_number routine to return more information via optional pointer arguments. In particular this lets us avoid converting string to floating point twice every time, yielding a general speedup.
2. Use is_number to filter out hexadecimal values and to enforce use of +nan, -nan, +inf, and -inf for NaN and infinity values, a la gawk.
3. Revised getfval to use information from is_number w.r.t. is the string wholely a number (123.45) or has a leading numeric component (123abc).  The latter is allowed when converting from string to floating point but not at other points in the awk code
4. Add a section to the man page at the end explaining all this. Is this much doc needed?

Rework floating point conversions.

---

lib.c

Though some implementations include this header indirectly through
string.h by default, the POSIX header that declares strcasecmp is
strings.h[0].
[0] https://pubs.opengroup.org/onlinepubs/9699919799/functions/strcasecmp.html

Include <strings.h> for strcasecmp

---

b.c

This resulted in the NUL terminator being written to the end of the buffer which was not the same as the end of the string.
That in turn caused garbage bytes from malloc() to be processed.
Also change the NUL termination to be less error prone by writing the NUL immediately after the last byte copied.
Reproducible with the following under valgrind:
```
echo '#!/usr/bin/awk' | awk \
'/^#! ?\/.*\/[a-z]{0,2}awk/ {sub(/^#! ?\/.*\/[a-z]{0,2}awk/,"#! awk"); print}'
```

Fix size computation in replace_repeat() for special_case REPEAT_WITH_Q.

---

lib.c
testdir/T.misc

Hello.
When getrec opens a file, it isn't setting the flag, innew, which the main i/o loop uses to signify that it's reading the first record. readrec then misconfigures the regex machine in a way that precludes ^-anchored matching.
This commit fixes the problem by restoring a line which was accidentally overlooked while porting NetBSD's regex-RS functionality. It also adds a test to T.misc to detect the issue, should it ever recur.
I looked over the [original diff](https://github.com/NetBSD/src/commit/3b57b2e4d3f25a12d8fe7a9835d30724f1b27528) that I sent zoulasc in 2012, in case any other bits were missing, but everything else seems to be in place.
In the following examples, `nawk` is the current (at time of writing) tip of the onetrueawk/awk master branch (c0f4e97). `./a.out` is `nawk` …

Fix regular expression RS ^-anchoring

---

lib.c
testdir/T.misc

I botched readrec's definition of a record, when I implemented
RS regular expression support. This is the relevant hunk from the
old diff:
```
-	return c == EOF && rr == buf ? 0 : 1;
+	isrec = *buf || !feof(inf);
+	   dprintf( ("readrec saw <%s>, returns %d\n", buf, isrec) );
+	return isrec;
```
Unlike testing with EOF, `*buf || !feof(inf)` is blind to stdio
errors. This can cause an infinite loop whose each iteration fabricates
an empty record.
The following demonstration uses standard terminal access control
policy to produce a persistent error condition. Note that the "i/o
error" message does not come from readrec(). It's produced much later
by closeall() at shutdown.
```
$ trap '' SIGTTIN && awk 'END {print NR}' &
[1] 33517
$ # After fg, type ^D
$ fg
trap '' SIGTTIN && awk 'END {print …
```

Fix readrec's definition of a record

---

main.c

IEEE Std 1003.1-2008 mandates that -F str be treated the same as -v
FS=str. For a null string, this was not the case. Since awk(1) documents
that a null string for FS has a specific behavior, make -F '' behave
consistently with -v FS="".

awk: Make -F '' and -v FS="" behave the same

---

run.c

getrec() returns 0 on EOF and leaves the contents of buf unchanged.
Fixes #133.

awkgetline: do not access unitialized data on EOF

---

FIXES
main.c
run.c

printstat and awkprintf are very clear: print statement errors
are fatal.
In Jan 2020, to prevent fatal print errors from masquerading
as fclose warnings, #63 changed every WARNING in closefile
and closeall to FATAL. This broke awk's close and getline
functions.
close no longer returns if there's an error, unless the stream
doesn't exist.
getline read errors still return -1, but they are no longer
ignorable. Eventually, one of the closing functions will inspect the
stream with ferror and call FATAL.
In Jul 2020, fatal stdout write errors which had been detectable by
closefile for a few months became invisible, a consequence of #89
switching standard streams from fclose (which reports flush errors) to
freopen (which ignores them). The earlier changes which broke
getline and close were …

Fix error handling in closefile and closeall

---

FIXES
main.c
run.c

stdinit initializes the first three slots of the files array
with statically allocated pathnames. closefile considers these
slots permanently statically allocated. openfile does not.
This discrepancy can leak memory: if a statically allocated slot
is vacated, openfile will put a malloc'd string where closefile
does not free.
To reconcile, either openfile must not reuse these slots or
stdinit and closefile must switch to dynamic allocation. I chose
the latter, because the result is a little simpler and less
interconnected than managing a partitioned array.
Here's a (contrived) demo with my system's output:
$ cat leak.sh
#!/bin/sh
awk=${1:-nawk}
yes | $awk '
BEGIN {
close("/dev/stderr")
system(rsz = "ps -p $PPID -o rsz=")
}
{ print > $0; close($0) }
NR % 50000 == 0 { system(rsz) }
NR == …

Eliminate file management memory leak

---

FIXES
lib.c
main.c
testdir/T.argv

After initialization, ARGV is supposed to be under the control of the
application (the awk script). However, when fulfilling the assignment
specified by a "name=value" operand, the implementation modifies the
operand's ARGV entry behind the application's back, truncating it.
This commit undoes the munge before returning control to the
application.
$ echo | ./master 'BEGIN { print ARGV[1] } { print ARGV[1] }' name=value
name=value
name
$ echo | ./a.out 'BEGIN { print ARGV[1] } { print ARGV[1] }' name=value
name=value
name=value
History: setclvar had been modifying its string argument without
ill-effect from the beginning (7th Edition UNIX, 1979) [1], when,
in 1989, SVR4 switched the source of the argument from argv to ARGV
[2]. The former cannot be accessed by the application, the latter …

Fix assignment operand handling to preserve ARGV

---

FIXES
main.c
tran.c

The new string value is always freeable (strdup'd by tostring), so
never mark it as DONTFREE.
```
$ paste <(./leak.sh master.out) <(./leak.sh fixed.out)
2564	 2464
7260	 2476
11948	 2476
16636	 2476
21324	 2476
26012	 2476
30700	 2476
35388	 2476
40076	 2476
44760	 2476
49448	 2476
$ cat leak.sh
#/bin/sh
awk=${1:-nawk}
yes abcdefghijklmnopqrstuvwxyz | $awk -v mem='ps -p $PPID -o rsz=' '
BEGIN            { system(mem) }
{ FS = $0 }
NR % 100000 == 0 { system(mem) }
NR == 1000000    { exit }
'
```
Every built-in mentioned in setfree is affected. `make check` completed uneventfully.
Thank you for taking the time to consider this contribution,
Miguel

Fix memory leak in string assignment to built-ins

---

awkgram.y

In every instance, after strnode has extracted the string, the node is leaked.
valgrind --leak-check=full ./a.out 'BEGIN {$0="a"; gensub("a", "z", "g")}'
valgrind --leak-check=full ./a.out 'BEGIN {gensub("a", "z", "g", "a")}'

Stop node leaks subsequent to strnode in gensub

---

awkgram.y
lex.c
testdir/T.misc

It is a mistake for the lexer not to make a copy of regexp literals, because the parser may need to shift more than one of them onto its stack as it searches for a matching rule.
For the following demonstration, the correct output is "1b":
$ echo ab | ./master 'sub(/a/, "b" ~ /b/)'
a1
The debugging output confirms that /b/ clobbered /a/, incorrectly modifying sub's first argument:
$ echo ab | ./master -d 'sub(/a/, "b" ~ /b/)' | grep reparse
reparse <b>
reparse <b>
One of those should have been "reparse \<a>".
I introduced this bug in a fix [1] for memory leaks discovered by Todd C. Miller [2]. This commit reverts my fix and applies a slightly modified version of Todd's recommendation (I omit the INDEX case because reg_expr is stored in a node).
[1] 577a67cc1f129e3ab240fcc47bf6f31cf6996b8e …

Fix regular expression clobbering in the lexer

---

parse.c
proto.h

There is no reason to cast to int anyway.

nodealloc should take a size_t rather than an int

---

run.c

There is a declaration of `int i` above the `if (ljust)` scope for use with a set of `for()` loops.  However, half the `for()` loops declare their own `int i` in the loop itself.  Both sets of `for()` loops should use the `int i` in the upper scope, or each `for()` loop should declare `int i` itself instead of shadowing the variable.

Use upper scope "int i" scope instead of declaring another in the for loop.

---

awk.h
b.c
main.c
run.c

This makes it possible to get the old awk behavior (where chars are bytes) by setting LC_CTYPE to C or POSIX.  The value of MB_CUR_MAX is cached since in many cases is actually a function.
No attempt is made to support arbitrary locales.  If the locale can support multi-byte characters, utf-8 will be used.  If not, 8-bit characters are used instead.
This also addresses #190

Disable utf-8 for non-multibyte locales, such as C or POSIX.

---

b.c

Now that awk stores chars as int we need to cast the Node * to int *.
Fixes the following script on big endian CPUs.
```
BEGIN { work="K"; gsub("[x]", "J", work); print work; }
```
Before fix:
```
JKJ
```
After:
```
K
```
Thanks to George Koehler for simplifying the test case.

Fix a bad cast to char * that causes incorrect results on big endian.

---

run.c

We need to use u8_strlen(), not strlen(), to compute the length. Otherwise, there may be an out of bounds write when writing the NUL terminator to set the length of the substring.

substr: fix buffer overflow with utf-8 strings

---

b.c

Hello, hope everyone is doing well.
I offer this rewrite of fnematch as an alternative to #211 and #213 (it also addresses the problems reported by @millert in #212).
I started from the original, byte-oriented version. The result might even be easier to follow. There is no nested loop and offset indices have been dropped in favor of pointers.
Miguel

Fix fnematch utf8 support

---

bugs-fixed/REGRESS
bugs-fixed/system-status.ok2
run.c

For some bizarre reason, the result of `system()` on MacOS was coming back as floating point numbers. I changed things to use `int` and only set the floating point result at the end. MacOS also doesn't seem to set the WCOREDUMP bit, so I added an additional `.ok` file and updated the file `bugs-fixed/REGRESS`.  That file now also has a `^G` in it so that one only need look for the BEL character to find errors.

Fix exit status of system on MacOS.

---

FIXES
b.c
main.c
run.c

C++ compilation was broken when we merged the UTF-8 support. This fixes things.
It's something of a band-aid. The mixing of signed and unsigned chars isn't all that healthy and ought to be really straightened out at some point.
In any case, it passes the test suite when compiled both with gcc and g++.  Enjoy.

Restore ability to compile with g++.

---

lib.c
testdir/T.argv
tran.c

The underlying table (array) may change due to, for example, "delete ARGV".  However, the Cell that stores ARGV should not change.  Also remove the ENVtab global which is never used outside of envinit(). Fixes issue #229.

Store the Cell containing ARGV instead of the ARGV table itself.

---

FIXES
b.c
main.c
makefile
run.c

The big change here is that C++ doesn't (yet, I guess) like C's indexed array initializers. I fixed some other warnings along the way.

Remove g++ compilation warnings.

---

FIXES.1e
README.md
TODO
awk.h
bugs-fixed/ofs-rebuild.awk
lex.c
proto.h
testdir/T.csconcat

Spelling fixes and remove unneeded prototype and extern.
Are yyback() yyinput() and yylook() prototypes needed?
popen() and pclose() prototypes duplicating system headers are for portability?

spelling and prototype fixes

---

bugs-fixed/system-status.awk
bugs-fixed/system-status.ok
bugs-fixed/system-status.ok2

/bin/sh on OpenBSD catches SIGHUP, which affects the return value of system() in the test. Use SIGKILL to ensure that the shell is terminated by a signal.
I've checked the new return value on FreeBSD, NetBSD, OpenBSD, macOS and Ubuntu.

Fix the system-status test on OpenBSD

---

awk.h
lex.c
run.c

This is the only missing time function compared to those two implementations.

Implement mktime() function for compatibility with mawk and gawk.
